"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, Bell, ChevronDown, Download, FileText, LayoutDashboard, Menu, Plus, Search, Settings, ShipWheel, Trash2, Upload, Users, X } from "lucide-react";
import type { AdminIdentity } from "../admin-auth";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";
import { PUBLIC_MEDIA_BUCKET } from "../../lib/supabase/config";

type Overview = {
  boats: Record<string, unknown>[]; applications: Record<string, unknown>[]; agents: Record<string, unknown>[]; posts: Record<string, unknown>[]; leadership: Record<string, unknown>[]; pages: Record<string, unknown>[]; categories: Record<string, unknown>[]; settings: Record<string,string>;
  stats: { boats:number;activeBoats:number;pendingApplications:number;agents:number };
};
type Entity = "houseboats"|"posts"|"leadership"|"agents"|"pages"|"categories";

const nav = [
  ["dashboard","Dashboard"],["houseboats","Houseboats"],["categories","Boat categories"],["applications","B2B applications"],["agents","Authorised agents"],["posts","News & notices"],["leadership","Leadership"],["pages","Pages & CMS"],["settings","Website settings"],
] as const;

const ADMIN_LOAD_TIMEOUT_MS = 20_000;

const formFields: Record<Entity, Array<[string,string,"text"|"number"|"textarea"|"select",string[]?]>> = {
  houseboats: [["membership_number","Membership number","text"],["slug","URL slug","text"],["name_en","Houseboat name","text"],["owner_name","Owner name","text"],["contact_number","Contact number","text"],["email","Business email","text"],["category","Boat type","select",["Wooden","Steel","Premium","Other"]],["status","Membership status","select",["active","pending","suspended","expired"]],["district","District","text"],["operating_area","Operating area","text"],["capacity","Capacity","number"],["cabins","Cabins","number"],["amenities","Amenities JSON","textarea"],["description_en","Description","textarea"],["last_verified_at","Last verified date","text"]],
  posts: [["slug","URL slug","text"],["category","Category","select",["Official Notice","News","Travel Advisory","Government Update","HOAB Event","Press Release","Member Announcement","Houseboat Fair"]],["title_en","Title","text"],["excerpt_en","Excerpt","textarea"],["content_en","Content","textarea"],["status","Publishing status","select",["draft","published","archived"]],["published_at","Publish date","text"]],
  leadership: [["panel","Leadership panel","select",["executive","advisory"]],["term","Committee term","text"],["name_en","Name","text"],["designation_en","Position","text"],["organization","Organisation (optional)","text"],["bio_en","Bio (optional)","textarea"],["status","Status","select",["current","previous"]],["display_order","Display order","number"]],
  agents: [["agent_id","Agent ID","text"],["agency_name","Agency name","text"],["contact_name","Contact person","text"],["phone","Phone","text"],["email","Email","text"],["website","Website","text"],["location","Location","text"],["status","Status","select",["authorised","suspended","expired","archived"]],["valid_since","Valid since","text"],["expires_at","Expires at","text"]],
  pages: [["page_key","Page key","text"],["title_en","Title","text"],["content_en","Content","textarea"],["published","Published (1/0)","number"]],
  categories: [["name_en","Category name","text"],["active","Active (1/0)","number"],["display_order","Display order","number"]],
};

function labelFor(tab:string){return nav.find(([key])=>key===tab)?.[1]??tab}
function value(record:Record<string,unknown>, key:string){return String(record[key]??"")}
function recordValue(record:Record<string,unknown>, key:string){return value(record,key)||value(record,key.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase()))}
function addLabelFor(entity:Entity){return entity==="houseboats"?"houseboat":entity==="leadership"?"committee member":entity==="categories"?"category":entity.slice(0,-1)}
function optionLabel(key:string,option:string){if(key==="panel")return option==="executive"?"Executive committee":"Advisory panel";if(key==="status")return option.charAt(0).toUpperCase()+option.slice(1);return option}

function jsonStringArray(record:Record<string,unknown>,key:string){const camel=key.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase());const raw=record[key]??record[camel];if(Array.isArray(raw))return raw.filter((item):item is string=>typeof item==="string"&&Boolean(item));if(typeof raw!=="string"||!raw.trim())return [];try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.filter((item):item is string=>typeof item==="string"&&Boolean(item)):[]}catch{return []}}

async function uploadAdminMedia(file:File,area:"houseboats"|"leadership"|"resources") {
  const metadata={area,name:file.name,contentType:file.type,size:file.size};
  const prepare=await fetch("/api/admin/media",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"prepare",...metadata})});
  const prepared=await prepare.json() as {key?:string;token?:string;error?:string};
  if(!prepare.ok||!prepared.key||!prepared.token)throw new Error(prepared.error||"Upload preparation failed");
  const {error:uploadError}=await createSupabaseBrowserClient().storage.from(PUBLIC_MEDIA_BUCKET).uploadToSignedUrl(prepared.key,prepared.token,file,{contentType:file.type});
  if(uploadError)throw new Error(uploadError.message);
  const complete=await fetch("/api/admin/media",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"complete",key:prepared.key,...metadata})});
  const completed=await complete.json() as {asset?:{publicUrl?:string;public_url?:string};error?:string};
  if(!complete.ok)throw new Error(completed.error||"Upload completion failed");
  const publicUrl=completed.asset?.publicUrl||completed.asset?.public_url;
  if(!publicUrl)throw new Error("The uploaded image URL was not returned");
  return publicUrl;
}

export default function AdminConsole({identity}:{identity:AdminIdentity}) {
  const [tab,setTab]=useState("dashboard"); const [navOpen,setNavOpen]=useState(false); const [data,setData]=useState<Overview|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [toast,setToast]=useState(""); const [editor,setEditor]=useState<{entity:Entity;record:Record<string,unknown>}|null>(null); const [search,setSearch]=useState("");
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2400)};
  const load=useCallback(async()=>{setLoading(true);setError("");const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),ADMIN_LOAD_TIMEOUT_MS);try{const response=await fetch("/api/admin/overview",{cache:"no-store",signal:controller.signal});const result=await response.json() as Overview&{error?:string};if(!response.ok)throw new Error(result.error||"Unable to load");setData(result)}catch(caught){setError(caught instanceof DOMException&&caught.name==="AbortError"?"The management system took too long to respond. Please retry.":caught instanceof Error?caught.message:"Unable to load admin data")}finally{window.clearTimeout(timeout);setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const save=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editor)return;const form=new FormData(event.currentTarget);const payload:Record<string,unknown>={};for(const [key,val] of form.entries())payload[key]=val; if(editor.record.id)payload.id=editor.record.id;for(const [key,,type] of formFields[editor.entity])if(type==="number"){const current=payload[key];payload[key]=current==="true"?1:current==="false"?0:Number(current||0)}const response=await fetch(`/api/admin/records/${editor.entity}`,{method:editor.record.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error||"Save failed");return}setEditor(null);notify("Saved successfully");await load()};
  const remove=async(entity:Entity,id:unknown)=>{if(!confirm(entity==="houseboats"?"Permanently delete this houseboat?":"Delete this record?"))return;const response=await fetch(`/api/admin/records/${entity}?id=${id}`,{method:"DELETE"});if(!response.ok){const r=await response.json() as {error?:string};setError(r.error||"Delete failed");return}notify("Record deleted");await load()};
  const review=async(id:unknown,status:string)=>{const internalNote=status==="additional_information_required"?prompt("What additional information is required?")||"":"";const response=await fetch(`/api/admin/applications/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,internalNote})});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error||"Review failed");return}notify(status==="approved"?"Application approved and agent created":"Application updated");await load()};
  const importBoats=async(file:File)=>{const form=new FormData();form.set("file",file);const response=await fetch("/api/admin/import/houseboats",{method:"POST",body:form});const result=await response.json() as {error?:string;imported?:number;updated?:number;invalid?:number};if(!response.ok){setError(result.error||"Import failed");return}notify(`Imported ${result.imported}, updated ${result.updated}, invalid ${result.invalid}`);await load()};
  const filtered=(records:Record<string,unknown>[])=>{const q=search.toLowerCase();return q?records.filter((record)=>Object.values(record).some((item)=>String(item??"").toLowerCase().includes(q))):records};
  const rowData=useMemo(()=>data?tab==="houseboats"?data.boats:tab==="categories"?data.categories:tab==="applications"?data.applications:tab==="agents"?data.agents:tab==="posts"?data.posts:tab==="leadership"?data.leadership:tab==="pages"?data.pages:[]:[],[data,tab]);
  const entity=(tab==="houseboats"||tab==="categories"||tab==="agents"||tab==="posts"||tab==="leadership"||tab==="pages")?tab as Entity:null;
  return <main className="admin-shell"><aside className={`admin-sidebar ${navOpen?"is-open":""}`}><div className="admin-brand"><a href="/" aria-label="Houseboat Owner's Association Bangladesh home"><img src="/brand/hoab-logo.png" alt="Houseboat Owner's Association Bangladesh" width="1396" height="606"/></a><small>Management system</small></div><button className="admin-sidebar__close" onClick={()=>setNavOpen(false)}><X/></button><nav>{nav.map(([key,label],index)=><button className={tab===key?"is-active":""} key={key} onClick={()=>{setTab(key);setNavOpen(false);setSearch("")}}>{index===0?<LayoutDashboard/>:key==="houseboats"?<ShipWheel/>:key==="applications"||key==="posts"?<FileText/>:key==="agents"||key==="leadership"?<Users/>:key==="settings"?<Settings/>:<span className="nav-dot"/>}<span>{label}</span>{key==="applications"&&data?.stats.pendingApplications?<em>{data.stats.pendingApplications}</em>:null}</button>)}</nav><div className="admin-help"><strong>{identity.displayName}</strong><p>{identity.email}</p><a href="/">View public site →</a><form action="/api/auth/signout" method="post"><button type="submit">Sign out →</button></form></div></aside><section className="admin-main"><header className="admin-topbar"><button className="admin-menu" onClick={()=>setNavOpen(true)}><Menu/></button><label><Search/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder={`Search ${labelFor(tab).toLowerCase()}…`}/></label><div><button className="icon-button"><Bell/><span/></button><button className="admin-user"><span>{identity.displayName.slice(0,2).toUpperCase()}</span><span><strong>{identity.displayName}</strong><small>{identity.role.replaceAll("_"," ")}</small></span><ChevronDown/></button></div></header><div className="admin-content">
    {error&&<div className="admin-error"><span>{error}</span><span><button onClick={()=>void load()}>Retry</button><button onClick={()=>setError("")} aria-label="Dismiss error"><X/></button></span></div>}
    {loading&&!data?<div className="admin-loading"><ShipWheel/><p>Loading management system…</p></div>:data&&<>
      <div className="admin-title"><div><p>HOAB central administration</p><h1>{labelFor(tab)}</h1><span>{tab==="leadership"?"Manage Executive Committee and Advisory Panel members":`Signed in as ${identity.email}`}</span></div><div className="admin-title__actions">{entity&&<button className="admin-primary" onClick={()=>setEditor({entity,record:entity==="leadership"?{panel:"executive",term:"2026–2028",status:"current",displayOrder:data.leadership.length+1}:{}})}><Plus/> Add {addLabelFor(entity)}</button>}{tab==="houseboats"&&<><label className="admin-import"><Upload/> Import CSV/XLSX<input type="file" accept=".csv,.xlsx" onChange={(e)=>{const file=e.target.files?.[0];if(file)void importBoats(file)}}/></label><a className="admin-secondary" href="/api/admin/export/houseboats"><Download/> Export</a></>}{tab==="agents"&&<a className="admin-secondary" href="/api/admin/export/agents"><Download/> Export</a>}</div></div>
      {tab==="dashboard"&&<Dashboard data={data} onNavigate={setTab}/>} {entity&&<RecordTable entity={entity} rows={filtered(rowData)} onEdit={(record)=>setEditor({entity,record})} onRemove={(id)=>void remove(entity,id)}/>} {tab==="applications"&&<Applications rows={filtered(rowData)} review={review}/>} {tab==="settings"&&<SettingsPanel settings={data.settings} onSaved={async()=>{notify("Settings updated");await load()}}/>}
    </>}
  </div></section>{editor&&<Editor state={editor} onClose={()=>setEditor(null)} onSave={save}/>} {toast&&<div className="toast"><BadgeCheck/>{toast}</div>}</main>
}

function Dashboard({data,onNavigate}:{data:Overview;onNavigate:(tab:string)=>void}){return <><div className="admin-stats"><article><span className="stat-icon stat-icon--green"><ShipWheel/></span><div><small>Registered boats</small><strong>{data.stats.boats}</strong><em>{data.stats.activeBoats} active</em></div></article><article><span className="stat-icon stat-icon--gold"><FileText/></span><div><small>Pending applications</small><strong>{data.stats.pendingApplications}</strong><em>Waiting for review</em></div></article><article><span className="stat-icon stat-icon--olive"><BadgeCheck/></span><div><small>Authorised agents</small><strong>{data.stats.agents}</strong><em>Publicly verified</em></div></article></div><div className="admin-grid"><section className="admin-panel admin-panel--wide"><div className="admin-panel__head"><div><h2>Recent B2B applications</h2><p>Prioritised by submission date</p></div><button onClick={()=>onNavigate("applications")}>View all →</button></div><Applications rows={data.applications.slice(0,5)} compact review={()=>{}}/></section><section className="admin-panel"><div className="admin-panel__head"><div><h2>Quick actions</h2><p>Common management tasks</p></div></div><div className="quick-actions"><button onClick={()=>onNavigate("houseboats")}><Plus/><span><strong>Add or import houseboats</strong><small>Manage the official registry</small></span></button><button onClick={()=>onNavigate("posts")}><FileText/><span><strong>Publish a notice</strong><small>Official updates and advisories</small></span></button><button onClick={()=>onNavigate("applications")}><Users/><span><strong>Review B2B applications</strong><small>Approve or request information</small></span></button></div></section><section className="admin-panel admin-panel--full"><div className="admin-panel__head"><div><h2>Recently updated houseboats</h2><p>Latest registry activity</p></div><button onClick={()=>onNavigate("houseboats")}>Manage directory →</button></div><div className="boat-admin-list">{data.boats.slice(0,5).map((boat)=><div key={String(boat.id)}><img src={value(boat,"coverImage")||value(boat,"cover_image")||"/images/hero-houseboat.jpg"} alt=""/><span><strong>{value(boat,"nameEn")||value(boat,"name_en")}</strong><small>{value(boat,"membershipNumber")||value(boat,"membership_number")} · {value(boat,"ownerName")||value(boat,"owner_name")}</small></span><em>{value(boat,"status")}</em></div>)}</div></section></div></>}

function RecordTable({entity,rows,onEdit,onRemove}:{entity:Entity;rows:Record<string,unknown>[];onEdit:(r:Record<string,unknown>)=>void;onRemove:(id:unknown)=>void}){const columns:Record<Entity,string[]>={houseboats:["coverImage","membershipNumber","nameEn","ownerName","contactNumber","category","status"],categories:["nameEn","active","displayOrder"],posts:["category","titleEn","publishedAt","status"],leadership:["photo","panel","nameEn","designationEn","term","displayOrder","status"],pages:["pageKey","titleEn","published"],agents:["agentId","agencyName","contactName","phone","status"]};const labels:Record<string,string>={coverImage:"Photo",photo:"Photo",panel:"Panel",membershipNumber:"Membership",nameEn:"Name",ownerName:"Owner",contactNumber:"Phone",titleEn:"Title",publishedAt:"Published",designationEn:"Position",agentId:"Agent ID",agencyName:"Agency",contactName:"Contact",pageKey:"Page key",displayOrder:"Order"};const style={gridTemplateColumns:entity==="leadership"?"74px minmax(125px,.8fr) minmax(170px,1.3fr) minmax(170px,1.3fr) 110px 70px 90px 110px":entity==="houseboats"?"74px 110px minmax(180px,1.3fr) minmax(150px,1fr) minmax(140px,1fr) 100px 90px 110px":`repeat(${columns[entity].length+1},minmax(110px,1fr))`};return <section className="admin-panel admin-record-panel"><div className="admin-record-table"><div className="admin-record-row is-head" style={style}>{columns[entity].map((column)=><span key={column}>{labels[column]||column.replace(/([A-Z])/g," $1")}</span>)}<span>Actions</span></div>{rows.map((row)=><div className={`admin-record-row ${entity==="leadership"?"is-leadership":""}`} style={style} key={String(row.id)}>{columns[entity].map((column)=>column==="photo"?<span className="leadership-table-photo" key={column} data-label="Photo">{recordValue(row,"photo")?<img src={recordValue(row,"photo")} alt=""/>:<span>{(recordValue(row,"name_en")||"?").slice(0,1)}</span>}</span>:column==="coverImage"?<span className="houseboat-table-photo" key={column} data-label="Photo">{recordValue(row,"cover_image")?<img src={recordValue(row,"cover_image")} alt=""/>:<ShipWheel/>}</span>:<span key={column} data-label={labels[column]||column}>{column==="panel"?optionLabel("panel",recordValue(row,column)):recordValue(row,column)||"—"}</span>)}<span className="record-actions"><button onClick={()=>onEdit(row)}>Edit</button><button className="danger" onClick={()=>onRemove(row.id)}><Trash2/></button></span></div>)}</div>{!rows.length&&<div className="empty-state"><Search/><h2>No records found</h2></div>}</section>}

function Applications({rows,review,compact=false}:{rows:Record<string,unknown>[];review:(id:unknown,status:string)=>void;compact?:boolean}){return <div className="admin-table"><div className="admin-table__row admin-table__header"><span>Application</span><span>Applicant</span><span>Submitted</span><span>Status</span><span/></div>{rows.map((app)=><div className="admin-table__row" key={String(app.id)}><span><strong>{value(app,"agencyName")||value(app,"agency_name")}</strong><small>{value(app,"referenceNumber")||value(app,"reference_number")}</small></span><span>{value(app,"contactName")||value(app,"contact_name")}</span><span>{value(app,"submittedAt")||value(app,"submitted_at")}</span><span><em className="status status--submitted">{(value(app,"status")||"submitted").replaceAll("_"," ")}</em></span><span className="record-actions">{!compact&&<><DocumentButton id={app.id}/><button onClick={()=>review(app.id,"under_review")}>Review</button><button onClick={()=>review(app.id,"approved")}>Approve</button><button onClick={()=>review(app.id,"additional_information_required")}>More info</button><button className="danger" onClick={()=>review(app.id,"rejected")}>Reject</button></>}</span></div>)}</div>}
function DocumentButton({id}:{id:unknown}){const [documents,setDocuments]=useState<Array<{id:number;originalName:string;documentType:string;size:number}>|null>(null);const load=async()=>{const response=await fetch(`/api/admin/applications/${id}/documents`);const result=await response.json() as {documents?:Array<{id:number;originalName:string;documentType:string;size:number}>};setDocuments(result.documents??[])};return <>{!documents?<button onClick={()=>void load()}>Documents</button>:documents.length?documents.map((document)=><a key={document.id} href={`/api/admin/applications/${id}/documents/${document.id}`} target="_blank" rel="noreferrer">{document.documentType.replaceAll("_"," ")}</a>):<small>No files</small>}</>}
function SettingsPanel({settings,onSaved}:{settings:Record<string,string>;onSaved:()=>void}){const [error,setError]=useState("");const save=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error||"Save failed");return}onSaved()};return <section className="admin-panel settings-panel"><form onSubmit={save}><h2>Global website settings</h2><p>These details are used across public contact and footer areas.</p><div className="form-grid"><label>Official organisation name<input name="site_name" defaultValue={settings.site_name}/></label><label>Official email<input name="official_email" defaultValue={settings.official_email}/></label><label>Official phone<input name="official_phone" defaultValue={settings.official_phone}/></label><label>Office hours<input name="office_hours" defaultValue={settings.office_hours}/></label><label className="span-2">Office address<textarea name="office_address" defaultValue={settings.office_address}/></label><label>Facebook URL<input name="facebook_url" defaultValue={settings.facebook_url}/></label><label>YouTube URL<input name="youtube_url" defaultValue={settings.youtube_url}/></label></div>{error&&<p className="form-error">{error}</p>}<button className="button button--dark">Save settings</button></form></section>}

function Editor({state,onClose,onSave}:{state:{entity:Entity;record:Record<string,unknown>};onClose:()=>void;onSave:(event:React.FormEvent<HTMLFormElement>)=>void}){
  const initialCover=recordValue(state.record,"cover_image");
  const initialGallery=jsonStringArray(state.record,"gallery");
  const effectiveCover=initialCover||initialGallery[0]||"";
  const [photo,setPhoto]=useState(recordValue(state.record,"photo"));
  const [boatImages,setBoatImages]=useState(()=>Array.from(new Set([effectiveCover,...initialGallery].filter(Boolean))));
  const [boatCover,setBoatCover]=useState(effectiveCover);
  const [uploading,setUploading]=useState(false);
  const [uploadError,setUploadError]=useState("");
  const uploadPhoto=async(file:File)=>{setUploadError("");setUploading(true);try{setPhoto(await uploadAdminMedia(file,"leadership"))}catch(caught){setUploadError(caught instanceof Error?caught.message:"Photo upload failed")}finally{setUploading(false)}};
  const uploadBoatPhotos=async(files:File[])=>{setUploadError("");if(boatImages.length+files.length>20){setUploadError("A houseboat can have up to 20 photos.");return}setUploading(true);const uploaded:string[]=[];try{for(const file of files)uploaded.push(await uploadAdminMedia(file,"houseboats"))}catch(caught){setUploadError(caught instanceof Error?caught.message:"Photo upload failed")}finally{if(uploaded.length){setBoatImages((current)=>Array.from(new Set([...current,...uploaded])));setBoatCover((current)=>current||uploaded[0])}setUploading(false)}};
  const removeBoatImage=(url:string)=>{const remaining=boatImages.filter((item)=>item!==url);setBoatImages(remaining);if(boatCover===url)setBoatCover(remaining[0]??"")};
  return <div className="admin-modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="admin-editor"><header><div><span>{state.record.id?"Edit record":"Create record"}</span><h2>{state.entity==="leadership"?"Leadership member":labelFor(state.entity)}</h2></div><button type="button" onClick={onClose}><X/></button></header><form onSubmit={onSave}>
    {state.entity==="houseboats"&&<section className="houseboat-image-editor"><div className="houseboat-image-editor__head"><div><h3>Houseboat photos</h3><p>Upload multiple JPG, PNG or WebP images. Select one image as the cover photo. Maximum 20 photos, 12 MB each.</p></div><label className="button button--outline"><Upload/>{uploading?"Uploading…":"Add photos"}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading} onChange={(e)=>{const files=Array.from(e.target.files??[]);if(files.length)void uploadBoatPhotos(files);e.currentTarget.value=""}}/></label></div>{boatImages.length?<div className="houseboat-image-grid">{boatImages.map((url,index)=><article className={url===boatCover?"is-cover":""} key={url}><img src={url} alt={`Houseboat photo ${index+1}`}/>{url===boatCover&&<span>Cover photo</span>}<div><button type="button" disabled={url===boatCover} onClick={()=>setBoatCover(url)}>{url===boatCover?"Selected":"Set as cover"}</button><button type="button" className="danger" onClick={()=>removeBoatImage(url)} aria-label={`Remove photo ${index+1}`}><Trash2/></button></div></article>)}</div>:<div className="houseboat-image-empty"><ShipWheel/><span>No photos added yet</span></div>}{uploadError&&<p className="form-error">{uploadError}</p>}<input type="hidden" name="cover_image" value={boatCover}/><input type="hidden" name="gallery" value={JSON.stringify(boatImages.filter((url)=>url!==boatCover))}/></section>}
    {state.entity==="leadership"&&<div className="leadership-photo-editor"><div className={`leadership-photo-preview ${photo?"has-image":""}`}>{photo?<img src={photo} alt="Selected committee member"/>:<Users/>}</div><div><h3>Member photo</h3><p>Upload a clear portrait. JPG, PNG or WebP, maximum 12 MB.</p><div className="leadership-photo-actions"><label className="button button--outline"><Upload/>{uploading?"Uploading…":photo?"Replace photo":"Upload photo"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={(e)=>{const file=e.target.files?.[0];if(file)void uploadPhoto(file);e.currentTarget.value=""}}/></label>{photo&&<button type="button" className="button button--outline" onClick={()=>setPhoto("")}><Trash2/> Remove</button>}</div>{uploadError&&<p className="form-error">{uploadError}</p>}<input type="hidden" name="photo" value={photo}/></div></div>}
    <div className="form-grid">{formFields[state.entity].map(([key,label,type,options])=><label className={type==="textarea"?"span-2":""} key={key}>{label}{type==="select"?<select name={key} defaultValue={recordValue(state.record,key)}>{options?.map((option)=><option key={option} value={option}>{optionLabel(key,option)}</option>)}</select>:type==="textarea"?<textarea name={key} defaultValue={recordValue(state.record,key)}/>:<input name={key} type={type} defaultValue={recordValue(state.record,key)}/>}</label>)}</div><div className="form-actions"><button type="button" className="button button--outline" onClick={onClose}>Cancel</button><button className="button button--gold" disabled={uploading}>{uploading?"Uploading photos…":"Save changes"}</button></div></form></section></div>
}
