"use client";

import { useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, CalendarDays, Check, Download, FileText, Mail, MapPin, Phone, Search, ShieldCheck, ShipWheel, Users } from "lucide-react";
import type { Boat, PublicData } from "../data";
import { BoatCard, Footer, Header, VerifiedBadge } from "./PublicSite";

export function AboutPage({ data, pageKey = "about" }: { data: PublicData; pageKey?: string }) {
  const [language, setLanguage] = useState<"en" | "bn">("en");
  const page = data.pages.find((item) => item.pageKey === pageKey) as Record<string, string> | undefined;
  const membership = pageKey === "membership";
  return <main><Header language={language} onLanguage={setLanguage} /><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">{membership ? "Membership" : "The association"}</span><h1>{language === "bn" ? page?.titleBn : page?.titleEn}</h1><p>{membership ? "Join the organised voice of Bangladesh’s houseboat community." : "Working for a safer, organised and sustainable houseboat tourism industry."}</p></div></section><section className="content-page"><div className="shell editorial-grid"><article className="editorial-main"><span className="section-kicker">{membership ? "Become a member" : "About HOAB"}</span><h2>{membership ? "A recognised place in a growing industry." : "Uniting the people who move the haor forward."}</h2><p>{language === "bn" ? page?.contentBn : page?.contentEn}</p><div className="content-pillars"><div><ShieldCheck /><h3>{membership ? "Verified membership" : "Our vision"}</h3><p>{membership ? "Complete documentation and operational verification." : "A trusted, responsible and globally recognised houseboat industry."}</p></div><div><Users /><h3>{membership ? "Industry voice" : "Our mission"}</h3><p>{membership ? "Representation through an organised national association." : "Represent owners, develop standards and strengthen cooperation."}</p></div><div><ShipWheel /><h3>{membership ? "Member network" : "Our responsibility"}</h3><p>{membership ? "Connect with owners, agents and public stakeholders." : "Protect Tanguar Haor while improving visitor confidence."}</p></div></div>{membership && <a className="button button--gold" href="mailto:membership@hoab.org.bd">Contact membership desk <ArrowRight size={16} /></a>}</article><aside className="editorial-aside"><div className="quote-card"><span>HOAB principle</span><blockquote>“The voyage together. The heritage forever.”</blockquote></div><div className="fact-card"><strong>{data.stats.registeredBoats}+</strong><span>verified public records</span></div><div className="fact-card"><strong>2026—2028</strong><span>current leadership term</span></div></aside></div></section><Footer /></main>;
}

export function LeadershipPage({ data }: { data: PublicData }) {
  const [language, setLanguage] = useState<"en" | "bn">("en");
  const panels = [["executive", "Executive committee"], ["advisory", "Advisory panel"]] as const;
  return <main><Header language={language} onLanguage={setLanguage} /><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">Term 2026—2028</span><h1>HOAB leadership</h1><p>Meet the committee and advisors guiding the association’s work.</p></div></section><section className="content-page"><div className="shell">{panels.map(([panel,label]) => <div className="leadership-list" key={panel}><div className="section-heading"><div><span className="section-kicker">Current term</span><h2>{label}</h2></div></div><div className="leadership-card-grid">{data.leadership.filter((item) => item.panel === panel).map((person) => <article key={person.id}><div className="person__avatar person__avatar--line"><span>{person.initials}</span></div><div><h3>{language === "bn" && person.nameBn ? person.nameBn : person.name}</h3><strong>{language === "bn" && person.roleBn ? person.roleBn : person.role}</strong><p>{language === "bn" && person.bioBn ? person.bioBn : person.bio || person.organization}</p></div></article>)}</div></div>)}</div></section><Footer /></main>;
}

export function B2BPage({ data }: { data: PublicData }) {
  const [language, setLanguage] = useState<"en" | "bn">("en");
  return <main><Header language={language} onLanguage={setLanguage} /><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">Official partner network</span><h1>Authorised B2B agents</h1><p>A transparent bridge between legitimate travel agencies and HOAB-registered operators.</p></div></section><section className="content-page"><div className="shell b2b-public-grid"><article><span className="section-kicker">Why this program exists</span><h2>A more professional way to work.</h2><p>The program reduces unverified intermediaries and connects legitimate agencies with a trusted houseboat network.</p><div className="requirement-list"><span><Check /> Valid trade license</span><span><Check /> Trade association certificate</span><span><Check /> NID of responsible person</span><span><Check /> Current agency and contact information</span></div><div className="content-actions"><a className="button button--gold" href="/b2b/apply">Apply online <ArrowRight size={16} /></a><a className="button button--outline" href="/verify-agent">Verify an agent</a></div></article><aside><span className="section-kicker">Current network</span><strong>{data.stats.authorisedAgents}</strong><p>authorised agents listed in the official database</p><a className="text-link" href="/b2b/agents">View agent directory <ArrowRight size={15} /></a></aside></div></section><Footer /></main>;
}

export function AgentsPage({ data, verifyOnly = false }: { data: PublicData; verifyOnly?: boolean }) {
  const [language, setLanguage] = useState<"en" | "bn">("en"); const [query,setQuery]=useState(""); const [searched,setSearched]=useState(false);
  const results = useMemo(() => { const q=query.toLowerCase().trim(); return q ? data.agents.filter((agent) => `${agent.agentId} ${agent.agencyName}`.toLowerCase().includes(q)) : verifyOnly ? [] : data.agents; },[data.agents,query,verifyOnly]);
  return <main><Header language={language} onLanguage={setLanguage} /><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">Official verification</span><h1>{verifyOnly ? "Verify an agent" : "Authorised agent directory"}</h1><p>Search by HOAB Agent ID or agency name.</p></div></section><section className="content-page"><div className="shell"><form className="public-verify" onSubmit={(event)=>{event.preventDefault();setSearched(true)}}><Search /><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="HOAB-A-0023 or agency name" /><button className="button button--gold">Verify</button></form>{results.length ? <div className="agent-grid">{results.map((agent) => <article key={String(agent.id)}><div className="agent-mark"><BadgeCheck /></div><span className="verified-badge"><BadgeCheck size={14} /> Verified</span><h2>{String(agent.agencyName)}</h2><strong>{String(agent.agentId)}</strong><p><MapPin /> {String(agent.location)}</p><p><Phone /> {String(agent.phone)}</p><small>Authorised since {String(agent.validSince)}</small></article>)}</div> : (searched || !verifyOnly) && <div className="empty-state"><Search /><h2>Not found / not currently authorised</h2><p>Check the ID or contact the HOAB secretariat.</p></div>}</div></section><Footer /></main>;
}

export function NewsPage({ data }: { data: PublicData }) {
  const [language,setLanguage]=useState<"en"|"bn">("en");
  return <main><Header language={language} onLanguage={setLanguage}/><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">Official communications</span><h1>News & notices</h1><p>Association updates, safety notices, events and industry information.</p></div></section><section className="content-page"><div className="shell news-list">{data.news.map((item)=><article key={item.id}><div><span>{item.category}</span><small><CalendarDays/> {new Date(item.date).toLocaleDateString()}</small></div><h2>{language==="bn"&&item.titleBn?item.titleBn:item.title}</h2><p>{language==="bn"&&item.excerptBn?item.excerptBn:item.excerpt}</p><a className="text-link" href={`/news/${item.slug}`}>Read full update <ArrowRight size={15}/></a></article>)}</div></section><Footer/></main>;
}

export function NewsDetailPage({ item }: { item: PublicData["news"][number] }) {
  const [language,setLanguage]=useState<"en"|"bn">("en");
  return <main><Header language={language} onLanguage={setLanguage}/><article className="article-page"><header><div className="shell"><span className="section-kicker section-kicker--light">{item.category}</span><h1>{language==="bn"&&item.titleBn?item.titleBn:item.title}</h1><p><CalendarDays/> {new Date(item.date).toLocaleDateString(language==="bn"?"bn-BD":"en-GB",{day:"numeric",month:"long",year:"numeric"})}</p></div></header><div className="shell article-body"><p className="article-lead">{language==="bn"&&item.excerptBn?item.excerptBn:item.excerpt}</p><div>{language==="bn"&&item.contentBn?item.contentBn:item.content}</div>{item.attachment&&<a className="button button--outline" href={item.attachment}><Download/> Download attachment</a>}<a className="text-link" href="/news">← Back to news</a></div></article><Footer/></main>;
}

export function EventsResourcesPage({ data, mode }: { data: PublicData; mode: "events"|"resources" }) {
  const [language,setLanguage]=useState<"en"|"bn">("en"); const rows=mode==="events"?data.events:data.resources;
  return <main><Header language={language} onLanguage={setLanguage}/><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">HOAB public information</span><h1>{mode==="events"?"Events":"Resources & downloads"}</h1><p>{mode==="events"?"Meetings, fairs and industry programs.":"Official forms, policies, guidelines and circulars."}</p></div></section><section className="content-page"><div className="shell resource-grid">{rows.map((raw)=>{const item=raw as Record<string,unknown>; return <article key={String(item.id)}><div className="resource-icon">{mode==="events"?<CalendarDays/>:<FileText/>}</div><span>{String(mode==="events"?item.status:item.category)}</span><h2>{String(language==="bn"&&item.nameBn?item.nameBn:mode==="events"?item.nameEn:language==="bn"&&item.titleBn?item.titleBn:item.titleEn)}</h2><p>{String(language==="bn"&&item.descriptionBn?item.descriptionBn:item.descriptionEn||"")}</p>{mode==="events"?<><strong>{String(item.eventDate)}</strong><small><MapPin/> {String(item.venue)}</small></>:<a className="text-link" href={String(item.fileUrl||item.externalUrl||"#")}>Open resource <ArrowRight size={15}/></a>}</article>})}</div></section><Footer/></main>;
}

export function ContactPage({ data }: { data: PublicData }) {
  const [language,setLanguage]=useState<"en"|"bn">("en"); const [state,setState]=useState({name:"",phone:"",email:"",subject:"",message:""}); const [status,setStatus]=useState("");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setStatus("Sending…");const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(state)});const result=await response.json() as {message?:string;error?:string};setStatus(response.ok?result.message||"Message received":result.error||"Unable to send");if(response.ok)setState({name:"",phone:"",email:"",subject:"",message:""});};
  return <main><Header language={language} onLanguage={setLanguage}/><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">HOAB Secretariat</span><h1>Contact HOAB</h1><p>Official enquiries, membership assistance and industry communication.</p></div></section><section className="content-page"><div className="shell contact-layout"><aside><h2>We’re here to help.</h2><p><MapPin/>{data.settings.office_address}</p><p><Phone/>{data.settings.official_phone}</p><p><Mail/>{data.settings.official_email}</p><small>Sunday–Thursday · 9:00 AM–5:00 PM</small></aside><form onSubmit={submit}><div className="form-grid"><label>Name<input required value={state.name} onChange={(e)=>setState({...state,name:e.target.value})}/></label><label>Phone<input value={state.phone} onChange={(e)=>setState({...state,phone:e.target.value})}/></label><label>Email<input required type="email" value={state.email} onChange={(e)=>setState({...state,email:e.target.value})}/></label><label>Subject<input required value={state.subject} onChange={(e)=>setState({...state,subject:e.target.value})}/></label><label className="span-2">Message<textarea required value={state.message} onChange={(e)=>setState({...state,message:e.target.value})}/></label></div>{status&&<p className="form-status">{status}</p>}<button className="button button--gold">Send message <ArrowRight size={16}/></button></form></div></section><Footer/></main>;
}

export function FAQPage() {
  const [language,setLanguage]=useState<"en"|"bn">("en"); const faqs=[
    ["What is a HOAB-registered houseboat?","A member operator whose record is active in the association registry."],
    ["How do I verify a boat?","Search the directory by boat name, owner or membership number."],
    ["How can an agency apply?","Complete the official B2B form and upload the required documents."],
    ["Does HOAB manage bookings?","No. Booking and commercial arrangements are made directly with each operator."],
  ];
  return <main><Header language={language} onLanguage={setLanguage}/><section className="page-hero"><div className="shell"><span className="section-kicker section-kicker--light">Help centre</span><h1>Frequently asked questions</h1></div></section><section className="content-page"><div className="shell faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section><Footer/></main>;
}

export function BoatDetailPage({ boat, related }: { boat: Boat; related: Boat[] }) {
  const [language,setLanguage]=useState<"en"|"bn">("en");
  return <main><Header language={language} onLanguage={setLanguage}/><section className="boat-detail-hero"><img src={boat.image} alt={boat.name}/><div className="boat-detail-hero__overlay"/><div className="shell"><VerifiedBadge/><span>{boat.membership}</span><h1>{language==="bn"&&boat.nameBn?boat.nameBn:boat.name}</h1><p>{boat.type} · {boat.operatingArea}</p></div></section><section className="content-page"><div className="shell boat-detail-layout"><article><span className="section-kicker">Verified houseboat profile</span><h2>Explore with confidence.</h2><p>{language==="bn"&&boat.descriptionBn?boat.descriptionBn:boat.description}</p><div className="boat-specs"><div><Users/><span>Capacity<strong>{boat.capacity} guests</strong></span></div><div><ShipWheel/><span>Cabins<strong>{boat.cabins}</strong></span></div><div><MapPin/><span>Operating area<strong>{boat.operatingArea}</strong></span></div><div><ShieldCheck/><span>Status<strong>Active member</strong></span></div></div><h3>Amenities</h3><div className="amenity-row">{boat.amenities.map((item)=><span key={item}><Check/>{item}</span>)}</div></article><aside><div className="verification-box"><BadgeCheck/><div><strong>HOAB verified member</strong><p>Last verified {boat.verified}</p></div></div><h3>Owner / operator</h3><strong>{boat.owner}</strong><a href={`tel:${boat.phone}`}><Phone/> {boat.phone}</a><a href={`mailto:${boat.email}`}><Mail/> {boat.email}</a><p>Bookings are arranged directly with the operator.</p></aside></div>{related.length>0&&<div className="shell related-boats"><div className="section-heading"><h2>More registered houseboats</h2></div><div className="boat-grid">{related.slice(0,3).map((item)=><BoatCard key={item.id} boat={item} onView={()=>location.assign(`/houseboats/${item.slug}`)}/>)}</div></div>}</section><Footer/></main>;
}
