import { desc } from "drizzle-orm";
import { canAdminWrite, requireAdminRequest } from "../../../admin-auth";
import { getDb, getUploads } from "../../../../db";
import { auditLogs, mediaAssets } from "../../../../db/schema";
import { seedDatabase } from "../../../../db/seed";

const allowed = new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
export async function GET(request:Request){const admin=await requireAdminRequest(request);if(!admin)return Response.json({error:"Unauthorised"},{status:401});await seedDatabase();return Response.json({media:await getDb().select().from(mediaAssets).orderBy(desc(mediaAssets.createdAt)).limit(100)})}
export async function POST(request:Request){const admin=await requireAdminRequest(request);if(!admin||!canAdminWrite(admin.role,"resources"))return Response.json({error:"Unauthorised"},{status:401});try{await seedDatabase();const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return Response.json({error:"File required"},{status:400});if(!allowed.has(file.type))return Response.json({error:"Only JPG, PNG, WebP and PDF files are allowed"},{status:400});if(file.size>12*1024*1024)return Response.json({error:"File exceeds 12 MB"},{status:400});const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-").slice(0,90);const key=`public/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${safe}`;await getUploads().put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type},customMetadata:{uploadedBy:admin.email}});const publicUrl=`/media/${key.replace(/^public\//,"")}`;const db=getDb();const [asset]=await db.insert(mediaAssets).values({storageKey:key,publicUrl,originalName:file.name,contentType:file.type,size:file.size,uploadedBy:admin.email}).returning();await db.insert(auditLogs).values({actorEmail:admin.email,action:"upload",entityType:"media",entityId:String(asset.id),summary:`Uploaded ${file.name}`,afterJson:JSON.stringify(asset)});return Response.json({asset},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"Upload failed"},{status:500})}}
