import type { PublicData } from "../app/data";

const boats: PublicData["boats"] = [
  { id: 1, slug: "haor-princess", name: "Haor Princess", nameBn: "হাওর প্রিন্সেস", membership: "HOAB-023", type: "Premium", status: "active", district: "Sylhet", operatingArea: "Tanguar Haor", capacity: 18, cabins: 6, airConditioned: true, image: "/images/hero-houseboat.jpg", gallery: [], owner: "Mahmudul Hasan", phone: "+880 1712 345 678", whatsapp: "+880 1712 345 678", email: "booking@haorprincess.example", website: "", facebookUrl: "", description: "A verified HOAB member operating responsible journeys across the haor.", descriptionBn: "হাওর অঞ্চলে দায়িত্বশীল ভ্রমণ পরিচালনাকারী একজন যাচাইকৃত HOAB সদস্য।", verified: "2026-08-01", featured: true, amenities: ["Air conditioning", "Life jackets", "Dining deck", "Wi-Fi"] },
  { id: 2, slug: "green-paradise", name: "Green Paradise", nameBn: "গ্রিন প্যারাডাইস", membership: "HOAB-041", type: "Wooden", status: "active", district: "Sunamganj", operatingArea: "Tanguar Haor", capacity: 20, cabins: 8, airConditioned: false, image: "/images/boat-paradise.jpg", gallery: [], owner: "Sajid Ahmed", phone: "+880 1811 245 870", whatsapp: "+880 1811 245 870", email: "hello@greenparadise.example", website: "", facebookUrl: "", description: "A verified HOAB member operating responsible journeys across the haor.", descriptionBn: "হাওর অঞ্চলে দায়িত্বশীল ভ্রমণ পরিচালনাকারী একজন যাচাইকৃত HOAB সদস্য।", verified: "2026-08-01", featured: true, amenities: ["Open deck", "Life jackets", "Private cabins", "Kitchen"] },
  { id: 3, slug: "nil-dorpon", name: "Nil Dorpôn", nameBn: "নীল দর্পণ", membership: "HOAB-058", type: "Steel", status: "active", district: "Habiganj", operatingArea: "Tanguar Haor", capacity: 14, cabins: 5, airConditioned: false, image: "/images/boat-shampan.jpg", gallery: [], owner: "Tanvir Hossain", phone: "+880 1914 861 224", whatsapp: "+880 1914 861 224", email: "reservations@nildorpon.example", website: "", facebookUrl: "", description: "A verified HOAB member operating responsible journeys across the haor.", descriptionBn: "হাওর অঞ্চলে দায়িত্বশীল ভ্রমণ পরিচালনাকারী একজন যাচাইকৃত HOAB সদস্য।", verified: "2026-08-01", featured: true, amenities: ["Family rooms", "Solar power", "Safety kit", "Upper deck"] },
  { id: 4, slug: "shampan", name: "Shampan", nameBn: "সাম্পান", membership: "HOAB-067", type: "Wooden", status: "active", district: "Sunamganj", operatingArea: "Tanguar Haor", capacity: 12, cabins: 4, airConditioned: false, image: "/images/boat-shampan.jpg", gallery: [], owner: "Abir Chowdhury", phone: "+880 1678 443 290", whatsapp: "", email: "sail@shampan.example", website: "", facebookUrl: "", description: "A verified HOAB member.", descriptionBn: "একজন যাচাইকৃত HOAB সদস্য।", verified: "2026-08-01", featured: false, amenities: ["Sun deck", "Meals", "Life jackets", "Generator"] },
  { id: 5, slug: "jol-torongo", name: "Jol Torongo", nameBn: "জল তরঙ্গ", membership: "HOAB-082", type: "Premium", status: "active", district: "Sylhet", operatingArea: "Tanguar Haor", capacity: 24, cabins: 9, airConditioned: true, image: "/images/hero-houseboat.jpg", gallery: [], owner: "Nafis Rahman", phone: "+880 1716 552 381", whatsapp: "", email: "journey@joltorongo.example", website: "", facebookUrl: "", description: "A verified HOAB member.", descriptionBn: "একজন যাচাইকৃত HOAB সদস্য।", verified: "2026-08-01", featured: false, amenities: ["Air conditioning", "Dining room", "Wi-Fi", "Guide"] },
  { id: 6, slug: "haor-bilash", name: "Haor Bilash", nameBn: "হাওর বিলাস", membership: "HOAB-096", type: "Steel", status: "active", district: "Sunamganj", operatingArea: "Tanguar Haor", capacity: 16, cabins: 6, airConditioned: false, image: "/images/boat-paradise.jpg", gallery: [], owner: "Rezwan Kabir", phone: "+880 1890 711 432", whatsapp: "", email: "contact@haorbilash.example", website: "", facebookUrl: "", description: "A verified HOAB member.", descriptionBn: "একজন যাচাইকৃত HOAB সদস্য।", verified: "2026-08-01", featured: false, amenities: ["Panoramic deck", "Life jackets", "Family cabins", "Meals"] },
];

const leadership: PublicData["leadership"] = [
  { id: 1, panel: "executive", term: "2026–2028", name: "Kazi Mahbubul Alam", nameBn: "কাজী মাহবুবুল আলম", role: "President", roleBn: "সভাপতি", organization: "HOAB", bio: "", bioBn: "", photo: "", initials: "KM" },
  { id: 2, panel: "executive", term: "2026–2028", name: "Syed Moinul Haque", nameBn: "সৈয়দ মঈনুল হক", role: "Senior Vice President", roleBn: "সিনিয়র সহ-সভাপতি", organization: "HOAB", bio: "", bioBn: "", photo: "", initials: "SM" },
  { id: 3, panel: "executive", term: "2026–2028", name: "Mohammad Arif Uddin", nameBn: "মোহাম্মদ আরিফ উদ্দিন", role: "General Secretary", roleBn: "সাধারণ সম্পাদক", organization: "HOAB", bio: "", bioBn: "", photo: "", initials: "MA" },
  { id: 4, panel: "executive", term: "2026–2028", name: "Tanvir Ahmed", nameBn: "তানভীর আহমেদ", role: "Treasurer", roleBn: "কোষাধ্যক্ষ", organization: "HOAB", bio: "", bioBn: "", photo: "", initials: "TA" },
  { id: 5, panel: "advisory", term: "2026–2028", name: "Dr. A. K. Enamul Haque", nameBn: "ড. এ. কে. এনামুল হক", role: "Tourism Advisor", roleBn: "পর্যটন উপদেষ্টা", organization: "", bio: "", bioBn: "", photo: "", initials: "DA" },
  { id: 6, panel: "advisory", term: "2026–2028", name: "S. M. Nazmul Islam", nameBn: "এস. এম. নাজমুল ইসলাম", role: "Safety Advisor", roleBn: "নিরাপত্তা উপদেষ্টা", organization: "", bio: "", bioBn: "", photo: "", initials: "SM" },
  { id: 7, panel: "advisory", term: "2026–2028", name: "Farida Yasmin", nameBn: "ফরিদা ইয়াসমিন", role: "Communications Advisor", roleBn: "যোগাযোগ উপদেষ্টা", organization: "", bio: "", bioBn: "", photo: "", initials: "FY" },
  { id: 8, panel: "advisory", term: "2026–2028", name: "Md. Nurul Islam", nameBn: "মো. নুরুল ইসলাম", role: "Industry Advisor", roleBn: "শিল্প উপদেষ্টা", organization: "", bio: "", bioBn: "", photo: "", initials: "MN" },
];

const news: PublicData["news"] = [
  { id: 1, slug: "monsoon-safety-protocol-2026", category: "Official Notice", date: "2026-08-01T10:00:00.000Z", title: "Monsoon safety protocol issued for all registered operators", titleBn: "নিবন্ধিত অপারেটরদের জন্য বর্ষা নিরাপত্তা প্রটোকল", excerpt: "Updated navigation, passenger-list and life-jacket guidance for the 2026 season.", excerptBn: "২০২৬ মৌসুমের জন্য নৌচালনা, যাত্রী তালিকা ও লাইফ জ্যাকেট সংক্রান্ত নির্দেশনা।", content: "Official HOAB communication. Further details can be updated from the management system.", contentBn: "অফিসিয়াল HOAB যোগাযোগ। বিস্তারিত ব্যবস্থাপনা সিস্টেম থেকে হালনাগাদ করা যাবে।", featuredImage: "/images/tanguar-haor.jpg", attachment: "", pinned: true },
  { id: 2, slug: "new-houseboats-verified", category: "Member Announcement", date: "2026-07-20T10:00:00.000Z", title: "Eight new houseboats complete HOAB verification", titleBn: "আটটি নতুন হাউসবোটের HOAB যাচাই সম্পন্ন", excerpt: "The new members have completed documentation and operational review.", excerptBn: "নতুন সদস্যরা নথি ও পরিচালনাগত পর্যালোচনা সম্পন্ন করেছে।", content: "Official HOAB communication.", contentBn: "অফিসিয়াল HOAB যোগাযোগ।", featuredImage: "/images/boat-paradise.jpg", attachment: "", pinned: false },
  { id: 3, slug: "tourism-roundtable-september", category: "HOAB Event", date: "2026-07-12T10:00:00.000Z", title: "Houseboat tourism roundtable set for September", titleBn: "সেপ্টেম্বরে হাউসবোট পর্যটন গোলটেবিল", excerpt: "Owners, agents and local stakeholders will meet in Sunamganj.", excerptBn: "মালিক, এজেন্ট ও স্থানীয় অংশীজন সুনামগঞ্জে মিলিত হবেন।", content: "Official HOAB communication.", contentBn: "অফিসিয়াল HOAB যোগাযোগ।", featuredImage: "/images/hero-houseboat.jpg", attachment: "", pinned: false },
];

export function getDemoPublicData(): PublicData {
  return {
    boats,
    leadership,
    news,
    agents: [{ id: 1, agentId: "HOAB-A-0023", agencyName: "Delta Routes", contactName: "Nusrat Jahan", phone: "+880 1711 222 333", email: "hello@deltaroutes.example", website: "", location: "Dhaka", logo: "", status: "authorised", validSince: "2026-05-01", expiresAt: "" }],
    events: [{ id: 1, nameEn: "HOAB Houseboat Tourism Roundtable", nameBn: "HOAB হাউসবোট পর্যটন গোলটেবিল", eventDate: "2026-09-18", startTime: "10:00", endTime: "", venue: "Sunamganj District Shilpakala Academy", descriptionEn: "An industry dialogue on standards, safety and responsible growth.", descriptionBn: "মান, নিরাপত্তা ও দায়িত্বশীল প্রবৃদ্ধি নিয়ে শিল্প সংলাপ।", poster: "", registrationUrl: "", status: "upcoming", published: true }],
    resources: [{ id: 1, titleEn: "B2B Registration Requirements", titleBn: "B2B নিবন্ধনের প্রয়োজনীয়তা", category: "Form", descriptionEn: "Required documents and application guidance.", descriptionBn: "প্রয়োজনীয় নথি ও আবেদন নির্দেশিকা।", fileUrl: "", externalUrl: "/b2b/apply", published: true, displayOrder: 1 }, { id: 2, titleEn: "Houseboat Safety Guidelines", titleBn: "হাউসবোট নিরাপত্তা নির্দেশিকা", category: "Guideline", descriptionEn: "Core passenger and operator safety guidance.", descriptionBn: "যাত্রী ও অপারেটর নিরাপত্তার মূল নির্দেশনা।", fileUrl: "", externalUrl: "", published: true, displayOrder: 2 }],
    pages: [{ id: 1, pageKey: "about", titleEn: "About HOAB", titleBn: "HOAB সম্পর্কে", contentEn: "HOAB represents, supports and organises Bangladesh’s growing houseboat tourism community.", contentBn: "HOAB বাংলাদেশের ক্রমবর্ধমান হাউসবোট পর্যটন সম্প্রদায়কে প্রতিনিধিত্ব, সহায়তা ও সংগঠিত করে।", published: true }, { id: 2, pageKey: "membership", titleEn: "Become a HOAB Member", titleBn: "HOAB সদস্য হোন", contentEn: "Eligible houseboat owners can complete verification and receive a unique membership number.", contentBn: "যোগ্য হাউসবোট মালিকরা যাচাই সম্পন্ন করে একটি অনন্য সদস্য নম্বর পেতে পারেন।", published: true }],
    settings: { site_name: "Houseboat Owners Association of Bangladesh", official_email: "info@hoab.org.bd", official_phone: "+880 1700 123 456", office_address: "HOAB Secretariat, Sunamganj, Bangladesh" },
    stats: { registeredBoats: boats.length, activeMembers: boats.length, authorisedAgents: 1, operatingDistricts: 3 },
  };
}
