import type { PublicData } from "../app/data";

const boats: PublicData["boats"] = [
  {
    "id": 75,
    "slug": "bashori-a-luxury-water-villa-hoab-089",
    "name": "Bashori A Luxurious Water Villa",
    "membership": "HOAB-089",
    "type": "Premium",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 32,
    "cabins": 10,
    "acRooms": 4,
    "nonAcRooms": 6,
    "attachedWashrooms": 9,
    "commonWashrooms": 2,
    "startingPrice": 4000,
    "airConditioned": true,
    "image": "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/exterior_1.jpg",
    "gallery": [
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/exterior_2.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/exterior_3.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/exterior_4.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/lobby_5.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/lobby_6.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/lobby_7.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/lobby_8.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/lobby_9.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/room_10.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/room_11.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/room_12.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/room_13.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/room_14.jpg",
      "/images/houseboats/bashori-a-luxury-water-villa-hoab-089/washroom_15.jpg"
    ],
    "owner": "Md Shahadat Hossain",
    "phone": "+8801682961926",
    "whatsapp": "+8801701315743",
    "email": "Bashorihouseboat@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1G1JuVxo5k/",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 82,
    "slug": "fantasy-a-luxury-house-boat-hoab-096",
    "name": "Fantasy A Luxury Houseboat",
    "membership": "HOAB-096",
    "type": "Premium",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 24,
    "cabins": 10,
    "acRooms": 10,
    "nonAcRooms": 0,
    "attachedWashrooms": 10,
    "commonWashrooms": 0,
    "startingPrice": 8000,
    "airConditioned": true,
    "image": "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/exterior_1.jpg",
    "gallery": [
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/exterior_2.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/exterior_3.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/exterior_4.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/exterior_5.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/lobby_6.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/lobby_7.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/room_10.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/room_11.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/room_12.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/room_8.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/room_9.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/washroom_13.jpg",
      "/images/houseboats/fantasy-a-luxury-house-boat-hoab-096/washroom_14.jpg"
    ],
    "owner": "H M Mominur Rahman Plabon",
    "phone": "+8801713625452",
    "whatsapp": "+8801713625452",
    "email": "mrplabon1990@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/fantasyluxuryboat",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 53,
    "slug": "hawai-tori-hoab-062",
    "name": "Hawai Tori",
    "membership": "HOAB-062",
    "type": "Wooden",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 16,
    "cabins": 6,
    "acRooms": 0,
    "nonAcRooms": 6,
    "attachedWashrooms": 6,
    "commonWashrooms": 1,
    "startingPrice": 4000,
    "airConditioned": false,
    "image": "/images/houseboats/hawai-tori-hoab-062/exterior_2.jpg",
    "gallery": [
      "/images/houseboats/hawai-tori-hoab-062/exterior_1.jpg",
      "/images/houseboats/hawai-tori-hoab-062/exterior_3.jpg",
      "/images/houseboats/hawai-tori-hoab-062/lobby_4.jpg",
      "/images/houseboats/hawai-tori-hoab-062/lobby_5.jpg",
      "/images/houseboats/hawai-tori-hoab-062/lobby_6.jpg",
      "/images/houseboats/hawai-tori-hoab-062/room_7.jpg",
      "/images/houseboats/hawai-tori-hoab-062/room_8.jpg",
      "/images/houseboats/hawai-tori-hoab-062/washroom_9.jpeg"
    ],
    "owner": "Azam Al Atik",
    "phone": "+8801675418794",
    "whatsapp": "+8801766840303",
    "email": "Hawaitori@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1G1JuVxo5k/",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 39,
    "slug": "ita-express-hoab-046",
    "name": "ITA Express",
    "membership": "HOAB-046",
    "type": "Steel",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 0,
    "cabins": 0,
    "acRooms": 0,
    "nonAcRooms": 0,
    "attachedWashrooms": 0,
    "commonWashrooms": 0,
    "startingPrice": 0,
    "airConditioned": false,
    "image": "/images/houseboats/ita-express-hoab-046/exterior_1.jpeg",
    "gallery": [
      "/images/houseboats/ita-express-hoab-046/exterior_2.png",
      "/images/houseboats/ita-express-hoab-046/lobby_3.jpeg",
      "/images/houseboats/ita-express-hoab-046/room_4.png",
      "/images/houseboats/ita-express-hoab-046/room_5.jpeg",
      "/images/houseboats/ita-express-hoab-046/room_6.jpeg",
      "/images/houseboats/ita-express-hoab-046/room_7.jpeg",
      "/images/houseboats/ita-express-hoab-046/room_8.jpeg",
      "/images/houseboats/ita-express-hoab-046/washroom_9.jpg"
    ],
    "owner": "Md Mainul Islam",
    "phone": "+8801856566238",
    "whatsapp": "",
    "email": "itaholidaysltd@gmail.com",
    "website": "",
    "facebookUrl": "",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 60,
    "slug": "the-royal-house-boat-hoab-073",
    "name": "Jolkunjo - The Royal Houseboat",
    "membership": "HOAB-073",
    "type": "Wooden",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 24,
    "cabins": 8,
    "acRooms": 0,
    "nonAcRooms": 8,
    "attachedWashrooms": 6,
    "commonWashrooms": 2,
    "startingPrice": 4500,
    "airConditioned": false,
    "image": "/images/houseboats/the-royal-house-boat-hoab-073/exterior_5.jpeg",
    "gallery": [
      "/images/houseboats/the-royal-house-boat-hoab-073/exterior_1.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/exterior_2.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/exterior_3.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/exterior_4.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/lobby_10.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/lobby_6.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/lobby_7.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/lobby_8.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/lobby_9.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/room_11.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/room_12.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/room_13.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/room_14.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/room_15.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/washroom_16.jpeg",
      "/images/houseboats/the-royal-house-boat-hoab-073/washroom_17.jpeg"
    ],
    "owner": "Monwar Hossain Rana",
    "phone": "+880185551817",
    "whatsapp": "+8801623183429",
    "email": "jolkunjoboat@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/jolkunjo",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 70,
    "slug": "kadombori-hoab-084",
    "name": "Kadombori - A Premium AC Houseboat in Tangua",
    "membership": "HOAB-084",
    "type": "Premium",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 35,
    "cabins": 10,
    "acRooms": 4,
    "nonAcRooms": 6,
    "attachedWashrooms": 10,
    "commonWashrooms": 0,
    "startingPrice": 8000,
    "airConditioned": true,
    "image": "/images/houseboats/kadombori-hoab-084/exterior_1.jpg",
    "gallery": [
      "/images/houseboats/kadombori-hoab-084/exterior_2.jpg",
      "/images/houseboats/kadombori-hoab-084/lobby_3.jpg",
      "/images/houseboats/kadombori-hoab-084/lobby_4.jpg",
      "/images/houseboats/kadombori-hoab-084/lobby_5.jpg",
      "/images/houseboats/kadombori-hoab-084/lobby_6.jpg",
      "/images/houseboats/kadombori-hoab-084/lobby_7.jpg",
      "/images/houseboats/kadombori-hoab-084/room_10.jpg",
      "/images/houseboats/kadombori-hoab-084/room_11.jpg",
      "/images/houseboats/kadombori-hoab-084/room_12.jpg",
      "/images/houseboats/kadombori-hoab-084/room_8.jpg",
      "/images/houseboats/kadombori-hoab-084/room_9.jpg",
      "/images/houseboats/kadombori-hoab-084/washroom_13.jpg"
    ],
    "owner": "Ashek Ahmed (Shahed)",
    "phone": "+8801711230623",
    "whatsapp": "+8801711230623",
    "email": "the.ashek@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1CEA2YrkQM/",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 48,
    "slug": "moon-of-tangua-hoab-055",
    "name": "Moon of Tangua",
    "membership": "HOAB-055",
    "type": "Wooden",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 28,
    "cabins": 7,
    "acRooms": 0,
    "nonAcRooms": 7,
    "attachedWashrooms": 0,
    "commonWashrooms": 0,
    "startingPrice": 6000,
    "airConditioned": false,
    "image": "/images/houseboats/moon-of-tangua-hoab-055/exterior_2.jpeg",
    "gallery": [
      "/images/houseboats/moon-of-tangua-hoab-055/exterior_1.jpeg",
      "/images/houseboats/moon-of-tangua-hoab-055/exterior_3.jpeg",
      "/images/houseboats/moon-of-tangua-hoab-055/lobby_4.jpeg",
      "/images/houseboats/moon-of-tangua-hoab-055/room_5.jpeg",
      "/images/houseboats/moon-of-tangua-hoab-055/washroom_6.jpeg"
    ],
    "owner": "Md Mayen Uddin Faruk",
    "phone": "+8801758086295",
    "whatsapp": "+8801810688210",
    "email": "travelwithruposhi@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1BhCeiELQN/?mibextid=wwXIfr",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 104,
    "slug": "senorita-the-aesthetic-houseboat-of-tpm-hoab-119",
    "name": "Senorita - The Aesthetic Houseboat Of TPM",
    "membership": "HOAB-119",
    "type": "Premium",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 40,
    "cabins": 10,
    "acRooms": 4,
    "nonAcRooms": 6,
    "attachedWashrooms": 10,
    "commonWashrooms": 0,
    "startingPrice": 6000,
    "airConditioned": true,
    "image": "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/exterior_3.jpg",
    "gallery": [
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/exterior_1.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/exterior_2.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/exterior_4.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/exterior_5.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/lobby_10.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/lobby_6.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/lobby_7.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/lobby_8.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/lobby_9.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/room_11.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/room_12.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/room_13.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/room_14.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/room_15.jpg",
      "/images/houseboats/senorita-the-aesthetic-houseboat-of-tpm-hoab-119/washroom_16.jpg"
    ],
    "owner": "Md. Sakhawat Hoque Polash",
    "phone": "+8801957539229",
    "whatsapp": "+8801805003892",
    "email": "polashmd97@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1DNUWypBC7/",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 88,
    "slug": "the-ark-a-tangua-houseboat-experience-hoab-103",
    "name": "THE ARK",
    "membership": "HOAB-103",
    "type": "Premium",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 40,
    "cabins": 11,
    "acRooms": 11,
    "nonAcRooms": 0,
    "attachedWashrooms": 10,
    "commonWashrooms": 1,
    "startingPrice": 8500,
    "airConditioned": true,
    "image": "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/exterior_2.jpg",
    "gallery": [
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/exterior_1.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/lobby_3.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/lobby_4.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/room_5.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/room_6.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/room_7.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/room_8.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/room_9.jpg",
      "/images/houseboats/the-ark-a-tangua-houseboat-experience-hoab-103/washroom_10.jpg"
    ],
    "owner": "AMIT ROY",
    "phone": "+8801792537704",
    "whatsapp": "+8801959766456",
    "email": "aramit78122@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/19PMzXe1wK/",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 91,
    "slug": "the-cruiser-jwel-of-tangua-hoab-106",
    "name": "The cruiser jewel of Tangua",
    "membership": "HOAB-106",
    "type": "Steel",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 35,
    "cabins": 10,
    "acRooms": 0,
    "nonAcRooms": 10,
    "attachedWashrooms": 8,
    "commonWashrooms": 2,
    "startingPrice": 5000,
    "airConditioned": false,
    "image": "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/exterior_1.jpg",
    "gallery": [
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/exterior_2.jpeg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/lobby_3.jpg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/room_4.jpg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/room_5.jpg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/room_6.jpg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/room_7.jpg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/room_8.jpg",
      "/images/houseboats/the-cruiser-jwel-of-tangua-hoab-106/washroom_9.jpg"
    ],
    "owner": "Mahbub Alam",
    "phone": "+8801742455699",
    "whatsapp": "+8801742455699",
    "email": "mahabubfakir94@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/19M9cheCpK/?mibextid=wwXIfr",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 87,
    "slug": "the-aesthetic-water-villa-hoab-102",
    "name": "জ্যোৎস্নার গল্প - The Aesthetic Water Villa",
    "membership": "HOAB-102",
    "type": "Steel",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 32,
    "cabins": 10,
    "acRooms": 0,
    "nonAcRooms": 10,
    "attachedWashrooms": 10,
    "commonWashrooms": 0,
    "startingPrice": 7000,
    "airConditioned": false,
    "image": "/images/houseboats/the-aesthetic-water-villa-hoab-102/exterior_2.jpeg",
    "gallery": [
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/exterior_1.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/exterior_3.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/exterior_4.png",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/exterior_5.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/lobby_10.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/lobby_6.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/lobby_7.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/lobby_8.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/lobby_9.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/room_11.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/room_12.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/room_13.jpeg",
      "/images/houseboats/the-aesthetic-water-villa-hoab-102/washroom_14.jpeg"
    ],
    "owner": "Mahbub Alam Papun",
    "phone": "+8801601001111",
    "whatsapp": "+8801337339661",
    "email": "jochnargolpo@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/jochnargolpo",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 89,
    "slug": "tangua-house-boat-hoab-104",
    "name": "যাদুকাটা এক্সপ্রেস (Tanagua House boat)",
    "membership": "HOAB-104",
    "type": "Wooden",
    "status": "active",
    "district": "",
    "operatingArea": "Tanguar Haor",
    "capacity": 18,
    "cabins": 6,
    "acRooms": 0,
    "nonAcRooms": 6,
    "attachedWashrooms": 0,
    "commonWashrooms": 2,
    "startingPrice": 4000,
    "airConditioned": false,
    "image": "/images/houseboats/tangua-house-boat-hoab-104/exterior_1.jpeg",
    "gallery": [
      "/images/houseboats/tangua-house-boat-hoab-104/exterior_2.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/exterior_3.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/exterior_4.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/lobby_5.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/room_6.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/room_7.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/room_8.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/room_9.jpeg",
      "/images/houseboats/tangua-house-boat-hoab-104/washroom_10.jpeg"
    ],
    "owner": "Ahmod Hasan Sayeem",
    "phone": "+8801775100786",
    "whatsapp": "+8801896151312",
    "email": "hasansayeem99@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1ERFNFJneB/?mibextid=wwXIfr",
    "description": "",
    "verified": "",
    "featured": false,
    "amenities": []
  },
  {
    "id": 230,
    "slug": "luna-the-floating-villa-hoab-127",
    "name": "LUNA THE FLOATING VILLA",
    "membership": "HOAB-127",
    "type": "Wooden",
    "status": "active",
    "district": "Sunamganj",
    "operatingArea": "Tanguar Haor",
    "capacity": 40,
    "cabins": 11,
    "acRooms": 0,
    "nonAcRooms": 11,
    "attachedWashrooms": 10,
    "commonWashrooms": 1,
    "startingPrice": 7500,
    "airConditioned": false,
    "image": "/images/houseboats/luna-the-floating-villa-hoab-127/exterior_1.jpeg",
    "gallery": [
      "/images/houseboats/luna-the-floating-villa-hoab-127/exterior_2.jpeg",
      "/images/houseboats/luna-the-floating-villa-hoab-127/lobby_3.jpeg",
      "/images/houseboats/luna-the-floating-villa-hoab-127/room_4.jpeg",
      "/images/houseboats/luna-the-floating-villa-hoab-127/room_5.jpeg",
      "/images/houseboats/luna-the-floating-villa-hoab-127/room_6.jpeg",
      "/images/houseboats/luna-the-floating-villa-hoab-127/room_7.jpeg",
      "/images/houseboats/luna-the-floating-villa-hoab-127/washroom_8.jpeg"
    ],
    "owner": "TANZEDUL ALAM",
    "phone": "+8801904177143",
    "whatsapp": "+8801904177143",
    "email": "rajontanzed45@gmail.com",
    "website": "",
    "facebookUrl": "",
    "description": "A verified HOAB member operating responsible journeys across Tanguar Haor.",
    "verified": "2026-08-01",
    "featured": false,
    "amenities": [
      "Open deck",
      "Life jackets",
      "Private cabins",
      "Dining area",
      "Safety equipment"
    ]
  },
  {
    "id": 231,
    "slug": "tangua-bilash-hoab-125",
    "name": "Tangua Bilash",
    "membership": "HOAB-125",
    "type": "Premium",
    "status": "active",
    "district": "Sunamganj",
    "operatingArea": "Tanguar Haor",
    "capacity": 35,
    "cabins": 12,
    "acRooms": 11,
    "nonAcRooms": 1,
    "attachedWashrooms": 11,
    "commonWashrooms": 1,
    "startingPrice": 7000,
    "airConditioned": true,
    "image": "/images/houseboats/tangua-bilash-hoab-125/exterior_4.png",
    "gallery": [
      "/images/houseboats/tangua-bilash-hoab-125/exterior_1.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/exterior_2.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/exterior_3.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/exterior_5.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/lobby_10.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/lobby_6.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/lobby_7.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/lobby_8.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/lobby_9.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/room_11.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/room_12.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/room_13.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/room_14.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/room_15.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/washroom_16.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/washroom_17.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/washroom_18.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/washroom_19.jpg",
      "/images/houseboats/tangua-bilash-hoab-125/washroom_20.jpg"
    ],
    "owner": "Mohsin",
    "phone": "+8801756201452",
    "whatsapp": "+8801315006644, +8801315004466, +8801315664422",
    "email": "mahimohsin175@gmail.com",
    "website": "",
    "facebookUrl": "https://www.facebook.com/share/1CJFcuS6cq/",
    "description": "A verified HOAB member operating responsible journeys across Tanguar Haor.",
    "verified": "2026-08-01",
    "featured": false,
    "amenities": [
      "Air conditioning",
      "Private cabins",
      "Dining deck",
      "Life jackets",
      "Safety equipment"
    ]
  }
];

const leadership: PublicData["leadership"] = [
  {
    "id": 15,
    "panel": "advisory",
    "term": "2026–2028",
    "name": "Dr. Taslim Amin Shovon",
    "role": "Director & CEO, Innoglobe Travel & Tours LTD. Ex. Director, Trade & Fair (TOAB)",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/4240c43a-0c54-4fe7-82e2-b4faf562a8dd-ChatGPT-Image-Aug-13--2026--04_57_26-PM--5-.png",
    "initials": "DT"
  },
  {
    "id": 16,
    "panel": "advisory",
    "term": "2026–2028",
    "name": "Mohammad Younus",
    "role": "Managing Director, Famous Creation PVT LTD. Ex. Director, Media and Public Relations (TOAB)",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/67c48c26-1315-4bcf-838e-0c934774acd2-ChatGPT-Image-Aug-13--2026--04_57_26-PM--4-.png",
    "initials": "MY"
  },
  {
    "id": 17,
    "panel": "advisory",
    "term": "2026–2028",
    "name": "Md. Faysal Mahmud",
    "role": "CEO, Unity Tourism BD Ex. General Secretary (ETAB)",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/32d8db33-cc22-4000-aef2-fbefa5cb426e-ChatGPT-Image-Aug-13--2026--04_57_26-PM--3-.png",
    "initials": "MF"
  },
  {
    "id": 18,
    "panel": "advisory",
    "term": "2026–2028",
    "name": "Md. Nazrul Islam",
    "role": "Proprietor & CEO, Pugmark Tours & Travels",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/fd6e2cd5-980f-4726-bb43-17157a0b1313-ChatGPT-Image-Aug-13--2026--04_57_25-PM--2-.png",
    "initials": "MN"
  },
  {
    "id": 19,
    "panel": "advisory",
    "term": "2026–2028",
    "name": "Md. Nehar Sarwar Ayon",
    "role": "Managing Director, Avijatrik Tourism LTD.",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/aaafe904-8511-48c7-a84f-5f01d98053cd-ChatGPT-Image-Aug-13--2026--04_57_25-PM--1-.png",
    "initials": "MN"
  },
  {
    "id": 9,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Md. Arafat Hossain",
    "role": "President",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/79ff53d1-b2d6-4410-ad42-800a126c0aa9-ChatGPT-Image-Aug-13--2026--05_05_53-PM--1-.png",
    "initials": "MA"
  },
  {
    "id": 10,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Mizanur Rahman",
    "role": "Vice President",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/14d150b7-47d1-422d-b259-470130031add-ChatGPT-Image-Aug-13--2026--05_05_54-PM--2-.png",
    "initials": "MR"
  },
  {
    "id": 11,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Md. Mayen Uddin Faruk",
    "role": "General Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/168afd26-5355-4b98-b5ea-eaf307ceb143-ChatGPT-Image-Aug-13--2026--05_05_59-PM--9-.png",
    "initials": "MM"
  },
  {
    "id": 12,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Deep Banik",
    "role": "Joint General Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/7aa0096a-993f-4ba3-962e-b9e2b4075419-ChatGPT-Image-Aug-27--2026--02_00_17-PM.png",
    "initials": "DB"
  },
  {
    "id": 13,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Md. Tarekur Rahman Pappu",
    "role": "Organizing Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/6204106b-6c27-4d7c-9919-9fd4f64f571b-ChatGPT-Image-Aug-13--2026--05_05_56-PM--5-.png",
    "initials": "MT"
  },
  {
    "id": 14,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Monowar Hossain Rana",
    "role": "Assistant Organizing Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-13/25ef37b7-0594-4bae-b583-cd0ef5b967fc-ChatGPT-Image-Aug-13--2026--05_05_57-PM--6-.png",
    "initials": "MH"
  },
  {
    "id": 20,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Ashfaq Zaman",
    "role": "Treasurer",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/2dfd3259-c954-410e-a485-d4c01b8ae20c-ChatGPT-Image-Aug-27--2026--01_48_52-PM.png",
    "initials": "AZ"
  },
  {
    "id": 21,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Md. Tajirul Islam Topu",
    "role": "Assistant Treasurer",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/0ba8605c-1b80-4925-b53a-49cc799ca2e2-ChatGPT-Image-Aug-27--2026--01_50_29-PM.png",
    "initials": "MT"
  },
  {
    "id": 22,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Ariyan Emon",
    "role": "Secretary for Environment, Development & Disaster Affairs",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/565b4545-8e62-46c6-b4b3-c2cff3b2ce67-ChatGPT-Image-Aug-27--2026--01_51_55-PM.png",
    "initials": "AE"
  },
  {
    "id": 28,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Sajidul Haque Huzaifa",
    "role": "Office Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/fc6849ae-c93c-4408-a7af-2978a4ddad0d-ChatGPT-Image-Aug-27--2026--02_00_33-PM.png",
    "initials": "SH"
  },
  {
    "id": 23,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Md. Saiful Islam (Raju)",
    "role": "Publicity Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/90ac45a6-3470-4b22-98e9-31f9c35bc72e-ChatGPT-Image-Aug-27--2026--01_52_03-PM.png",
    "initials": "MS"
  },
  {
    "id": 27,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Shahadat Hossain",
    "role": "Assistant Office Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/c809032a-6b89-4f22-a015-fb4e688274d0-ChatGPT-Image-Aug-27--2026--02_00_25-PM.png",
    "initials": "SH"
  },
  {
    "id": 24,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Labib Hossain Joy",
    "role": "Assistant Publicity Secretary",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/fb4de96e-6668-4bea-9b1f-c7f238ae7bd9-ChatGPT-Image-Aug-27--2026--01_52_09-PM.png",
    "initials": "LH"
  },
  {
    "id": 25,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Sadaf Sarkar Sabbir",
    "role": "Assistant Secretary for Environment, Development & Disaster Affairs",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/d3fe0cc8-9427-4d91-bdf1-7f7a1b6b6d8a-ChatGPT-Image-Aug-27--2026--01_52_20-PM.png",
    "initials": "SS"
  },
  {
    "id": 26,
    "panel": "executive",
    "term": "2026–2028",
    "name": "Abdur Rahman Rifan",
    "role": "Secretary for Sports & Cultural Affairs",
    "organization": "",
    "bio": "",
    "photo": "https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/f44cad21-12c8-41a7-92c3-100eebb62a56-ChatGPT-Image-Aug-27--2026--01_52_28-PM.png",
    "initials": "AR"
  }
];

const news: PublicData["news"] = [
  {
    "id": 4,
    "slug": "chittagong-travel-mart-2026",
    "category": "HOAB Event",
    "date": "2026-08-28 06:00:00.000000+00",
    "title": "চট্টগ্রাম ট্রাভেল মার্ট ২০২৬ এ অংশ নিচ্ছে Houseboat Owner’s Association of Bangladesh (HOAB)",
    "excerpt": "আগামী ৮–১০ অক্টোবর দ্য পেনিনসুলা চট্টগ্রামে ১৭তম আন্তর্জাতিক পর্যটন মেলায় প্রিমিয়াম হাউসবোট, আকর্ষণীয় ভ্রমণ প্যাকেজ ও বিশেষ ডিসকাউন্ট নিয়ে থাকছে হুয়াব (প্যাভিলিয়ন-২, স্টল ২৬ ও ২৭)।",
    "content": "চট্টগ্রামের ভ্রমণপিপাসু ও নৌ পর্যটন প্রেমীদের জন্য দুর্দান্ত সুযোগ! আগামী ০৮ থেকে ১০ অক্টোবর ২০২৬, দ্য পেনিনসুলা চট্টগ্রামে আয়োজিত হতে যাচ্ছে Chittagong Travel Mart - 17th International Tourism Fair 2026।\n\nবাংলাদেশের অনন্য হাউসবোট পর্যটনকে আরও সমৃদ্ধ করতে এবং আপনাদের স্বপ্নের নৌ ভ্রমণের সেরা অভিজ্ঞতা ও বিশেষ ডিসকাউন্ট প্যাকেজগুলো তুলে ধরতে এই মেলায় অংশ নিচ্ছে Houseboat Owner’s Association of Bangladesh (HOAB)।\n\nআমাদের প্যাভিলিয়নে এসে সরাসরি বিভিন্ন রুটের প্রিমিয়াম হাউসবোট, ভ্রমণ প্যাকেজ ও বুকিং সংক্রান্ত যাবতীয় তথ্য সংগ্রহ করার জন্য সবাইকে সাদর আমন্ত্রণ জানানো হচ্ছে।\n\nমেলার বিস্তারিত:\n• ইভেন্ট: Chittagong Travel Mart - 17th International Tourism Fair 2026\n• তারিখ: ০৮, ০৯ ও ১০ অক্টোবর ২০২৬\n• স্থান: ডালিয়া হল, দ্য পেনিনসুলা চট্টগ্রাম, জিইসি সার্কেল, চট্টগ্রাম\n• প্যাভিলিয়ন: Pavillion - 2\n• স্টল নম্বর: Stall 26 & 27\n\nদেখা হচ্ছে দ্য পেনিনসুলা চট্টগ্রামে!",
    "featuredImage": "/images/news/chittagong-travel-mart-2026.jpg",
    "attachment": "",
    "pinned": true
  },
  {
    "id": 1,
    "slug": "monsoon-safety-protocol-2026",
    "category": "Official Notice",
    "date": "2026-08-13 07:26:39.900545+00",
    "title": "Monsoon safety protocol issued for all registered operators",
    "excerpt": "Updated navigation, passenger-list and life-jacket guidance for the 2026 season.",
    "content": "Official HOAB communication. Further details can be updated from the management system.",
    "featuredImage": "",
    "attachment": "",
    "pinned": true
  },
  {
    "id": 2,
    "slug": "new-houseboats-verified",
    "category": "Member Announcement",
    "date": "2026-08-13 07:26:39.900545+00",
    "title": "Eight new houseboats complete HOAB verification",
    "excerpt": "The new members have completed documentation and operational review.",
    "content": "Official HOAB communication. Further details can be updated from the management system.",
    "featuredImage": "",
    "attachment": "",
    "pinned": false
  },
  {
    "id": 3,
    "slug": "tourism-roundtable-september",
    "category": "HOAB Event",
    "date": "2026-08-13 07:26:39.900545+00",
    "title": "Houseboat tourism roundtable set for September",
    "excerpt": "Owners, agents and local stakeholders will meet in Sunamganj.",
    "content": "Official HOAB communication. Further details can be updated from the management system.",
    "featuredImage": "",
    "attachment": "",
    "pinned": false
  }
];

export function getDemoPublicData(): PublicData {
  return {
    boats,
    leadership,
    news,
    agents: [],
    events: [
  {
    "id": 1,
    "name": "HOAB Houseboat Tourism Roundtable",
    "eventDate": "2026-09-18",
    "startTime": "10:00",
    "endTime": "",
    "venue": "Sunamganj District Shilpakala Academy",
    "description": "An industry dialogue on standards, safety and responsible growth.",
    "poster": "",
    "registrationUrl": "",
    "status": "upcoming"
  }
],
    resources: [
  {
    "id": 1,
    "title": "B2B Registration Requirements",
    "category": "Form",
    "description": "Required documents and application guidance.",
    "fileUrl": "",
    "externalUrl": "/b2b/apply",
    "displayOrder": 1
  },
  {
    "id": 2,
    "title": "Houseboat Safety Guidelines",
    "category": "Guideline",
    "description": "Core passenger and operator safety guidance.",
    "fileUrl": "",
    "externalUrl": "",
    "displayOrder": 2
  }
],
    pages: [
  {
    "id": 1,
    "pageKey": "about",
    "title": "About HOAB",
    "content": "HOAB represents, supports and organises Bangladesh’s growing houseboat tourism community. The association promotes verified membership, operational standards, responsible tourism and stronger cooperation among owners, agents and public stakeholders."
  },
  {
    "id": 2,
    "pageKey": "membership",
    "title": "Become a HOAB Member",
    "content": "Eligible houseboat owners can contact the secretariat, prepare ownership and operational documents, complete verification and receive a unique membership number."
  }
],
    settings: {
  "seed_version": "1",
  "site_name": "Houseboat Owners Association of Bangladesh",
  "official_email": "houseboatownersassociation70@gmail.com",
  "official_phone": "+880 1700 123 456",
  "office_hours": "",
  "office_address": "HOAB Secretariat, Sunamganj, Bangladesh",
  "facebook_url": "",
  "youtube_url": "",
  "hero_images": "[\"https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/9b85d56e-84a1-4c80-b265-cac174d238c4-509002242_651786941231807_7156249288481311533_n.jpg\",\"https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/9d4796c5-adc7-4d76-afe2-480e7f897aa1-686935850_3557535701061841_8566096805960670075_n.jpg\",\"https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/d16df63f-6565-469a-8494-2b2b7e9c1669-721128950_880096285108466_8536780628806773177_n.jpg\",\"https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/01831558-0374-4424-9625-bad182f854cd-IMG_0588.JPG\",\"https://odepgynqdwlmerhejhlk.supabase.co/storage/v1/object/public/public-media/2026-08-27/c8623100-7097-47b8-b5ab-86156663a6f3-IMG_0589.JPG\"]"
},
    stats: {
      registeredBoats: 105,
      activeMembers: 105,
      authorisedAgents: 1,
      operatingDistricts: 1
    },
  };
}
